apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: order-processing-db
  name: order-processing-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: order-processing-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/microservices-default: "true"
        io.kompose.service: order-processing-db
    spec:
      containers:
        - env:
            - name: PGDATABASE
              value: ordersdb
            - name: PGHOST
              value: order-processing-db
            - name: PGPASSWORD
              value: password
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: postgres
            - name: PORT
              value: "3001"
            - name: POSTGRES_DB
              value: ordersdb
            - name: POSTGRES_HOST
              value: order-processing-db
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: postgres
          image: postgres:13
          name: order-processing-db
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
status: {}
